cwlVersion: v1.2
class: CommandLineTool

label: HEATWISE Patch Extraction Pipeline Adapter
doc: |
  Internal HEATWISE LCZ pipeline adapter for patch extraction.

  The tool combines the STAC output produced by heatwise-hsi-lst-prep with
  the original Sentinel-2 product, injects the dynamically staged label
  shapefile into the patch-extraction configuration, constructs the STAC
  interface expected by heatwise-patch-extraction, and invokes the upstream
  processor.

  The scientific patch-extraction logic remains entirely in
  heatwise-patch-extraction. This tool only adapts pipeline inputs.

requirements:

  DockerRequirement:
    dockerPull: ghcr.io/heatwise-lcz/heatwise-patch-extraction-pipeline:0.1.1

baseCommand: python

arguments:
  - /app/run_patch_extraction.py

inputs:

  template:
    type: File
    label: patch extraction configuration template
    doc: |
      Patch-extraction YAML configuration containing processing parameters.
      The labels.shp path is injected dynamically by the pipeline adapter.
    inputBinding:
      prefix: --template

  prep_dir:
    type: Directory
    label: preprocessing output
    doc: |
      Complete STAC-enabled output directory produced by
      heatwise-hsi-lst-prep. Its catalog.json is used to discover the
      hsi_bs and optional lst products.
    inputBinding:
      prefix: --prep-dir

  sentinel2:
    type: File
    label: Sentinel-2 raster
    doc: |
      Original Sentinel-2 raster used together with the processed HSI and
      optional LST products.
    inputBinding:
      prefix: --sentinel2

  labels_dir:
    type: Directory
    label: LCZ labels directory
    doc: |
      Directory containing the label shapefile and its associated sidecar
      files (.shx, .dbf, .prj, .cpg).
    inputBinding:
      prefix: --labels-dir

  labels_basename:
    type: string
    label: labels basename
    doc: |
      Basename of the label shapefile without the .shp extension.
    inputBinding:
      prefix: --labels-basename

  output_h5_name:
    type: string
    label: output HDF5 filename
    default: patches.h5
    doc: |
      Filename of the geographically isolated HDF5 patch dataset.
    inputBinding:
      prefix: --output-h5

outputs:

  output:
    type: Directory
    doc: |
      Complete working directory containing the HDF5 patch dataset and the
      STAC catalog generated by heatwise-patch-extraction.
    outputBinding:
      glob: "."
