cwlVersion: v1.2
class: CommandLineTool

label: HEATWISE LCZ Training
doc: |
  Vendored HEATWISE LCZ_HMSSNet training tool used by the LCZ pipeline.

  The training dataset is supplied through a staged STAC Directory whose
  catalog.json references the patch HDF5 product generated by
  heatwise-patch-extraction through the `patch_h5` asset.

  The processor writes model checkpoints, evaluation metrics, summary files,
  and an output STAC catalog to the CWL working directory.

requirements:

DockerRequirement:
  dockerPull: ghcr.io/esa-heatwise/heatwise-lcz-classification:eoap-compliance

  InlineJavascriptRequirement: {}

baseCommand: python

arguments:
  - /app/processor.py
  - train

inputs:

  input_catalog:
    type: Directory
    label: input STAC catalog
    doc: |
      Directory containing catalog.json and the associated STAC Item
      referencing the patch HDF5 training dataset through the `patch_h5`
      asset.
    inputBinding:
      prefix: --input-catalog
      valueFrom: $(self.path + "/catalog.json")

  config:
    type: File
    label: training configuration
    doc: |
      YAML configuration defining LCZ_HMSSNet training and evaluation
      parameters, including modality experiments, number of classes,
      batch size, epochs, early stopping, scaling, and random seed.
    inputBinding:
      prefix: --config

  output_dir:
    type: string
    label: output directory
    default: "."
    doc: |
      Output directory path relative to the CWL working directory.
    inputBinding:
      prefix: --output-dir

outputs:

  output:
    type: Directory
    doc: |
      Complete training working directory containing model checkpoints,
      evaluation metrics, summary files, training artifacts, and the
      generated STAC catalog.
    outputBinding:
      glob: "."
