cwlVersion: v1.2
class: CommandLineTool

label: HEATWISE LCZ Prediction Pipeline Adapter
doc: |
  Internal HEATWISE LCZ pipeline adapter for whole-scene prediction.

  The tool adapts the STAC output produced by heatwise-hsi-lst-prep to the
  input interface expected by heatwise-lcz-classification, adds the original
  Sentinel-2 product, selects the trained model checkpoint corresponding to
  the requested experiment, and invokes the upstream prediction processor.

  The upstream processor generates the LCZ GeoTIFF, optional preview PNG,
  and output STAC catalog. No scientific prediction logic is implemented
  in this adapter.

requirements:

  DockerRequirement:
    dockerPull: ghcr.io/heatwise-lcz/heatwise-lcz-classification-pipeline:0.1.1

baseCommand: python

arguments:
  - /app/run_predict.py

inputs:

  template:
    type: File
    label: prediction configuration
    doc: |
      Prediction YAML configuration containing inference and model
      parameters. EO raster paths and model weights are supplied separately
      by the pipeline adapter.
    inputBinding:
      prefix: --template

  prep_dir:
    type: Directory
    label: preprocessing output
    doc: |
      Complete STAC-enabled output directory produced by
      heatwise-hsi-lst-prep. Its catalog.json is used to discover the
      hsi_bs and optional lst products.
    inputBinding:
      prefix: --prep-dir

  sentinel2:
    type: File
    label: Sentinel-2 raster
    doc: |
      Original Sentinel-2 raster used together with the preprocessed HSI
      and optional LST products.
    inputBinding:
      prefix: --sentinel2

  train_dir:
    type: Directory
    label: training output
    doc: |
      Complete output directory produced by LCZ training. The adapter
      locates best_model_<experiment>.pth within this directory.
    inputBinding:
      prefix: --train-dir

  experiment_name:
    type: string
    label: experiment name
    doc: |
      Training experiment whose best_model_<experiment>.pth checkpoint
      should be used for prediction.
    inputBinding:
      prefix: --experiment-name

  output_dir_name:
    type: string
    label: prediction output directory
    default: "."
    doc: |
      Output directory path relative to the CWL working directory.
      By default, prediction products are written directly to the working
      directory.
    inputBinding:
      prefix: --output-dir

outputs:

  output:
    type: Directory
    doc: |
      Complete working directory containing the LCZ classification GeoTIFF,
      optional preview PNG, and STAC catalog generated by the upstream
      prediction processor.
    outputBinding:
      glob: "."
